/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei API
 * API documentation for Sunrei project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSunreiParams
 */
export interface GetSunreiParams {
    /**
     * ID of the Sunrei to retrieve
     * @type {number}
     * @memberof GetSunreiParams
     */
    id?: number;
}

/**
 * Check if a given object implements the GetSunreiParams interface.
 */
export function instanceOfGetSunreiParams(value: object): value is GetSunreiParams {
    return true;
}

export function GetSunreiParamsFromJSON(json: any): GetSunreiParams {
    return GetSunreiParamsFromJSONTyped(json, false);
}

export function GetSunreiParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSunreiParams {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function GetSunreiParamsToJSON(json: any): GetSunreiParams {
    return GetSunreiParamsToJSONTyped(json, false);
}

export function GetSunreiParamsToJSONTyped(value?: GetSunreiParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

