/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei API
 * API documentation for Sunrei project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SunreiDTO } from './SunreiDTO';
import {
    SunreiDTOFromJSON,
    SunreiDTOFromJSONTyped,
    SunreiDTOToJSON,
    SunreiDTOToJSONTyped,
} from './SunreiDTO';

/**
 * 
 * @export
 * @interface GetSunreiResult
 */
export interface GetSunreiResult {
    /**
     * 
     * @type {SunreiDTO}
     * @memberof GetSunreiResult
     */
    sunrei?: SunreiDTO;
}

/**
 * Check if a given object implements the GetSunreiResult interface.
 */
export function instanceOfGetSunreiResult(value: object): value is GetSunreiResult {
    return true;
}

export function GetSunreiResultFromJSON(json: any): GetSunreiResult {
    return GetSunreiResultFromJSONTyped(json, false);
}

export function GetSunreiResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSunreiResult {
    if (json == null) {
        return json;
    }
    return {
        
        'sunrei': json['sunrei'] == null ? undefined : SunreiDTOFromJSON(json['sunrei']),
    };
}

export function GetSunreiResultToJSON(json: any): GetSunreiResult {
    return GetSunreiResultToJSONTyped(json, false);
}

export function GetSunreiResultToJSONTyped(value?: GetSunreiResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sunrei': SunreiDTOToJSON(value['sunrei']),
    };
}

