/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei API
 * API documentation for Sunrei project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageDTO
 */
export interface ImageDTO {
    /**
     * 
     * @type {string}
     * @memberof ImageDTO
     */
    id?: string;
    /**
     * URL of the image
     * @type {string}
     * @memberof ImageDTO
     */
    url?: string;
    /**
     * Width of the image in pixels
     * @type {number}
     * @memberof ImageDTO
     */
    width?: number;
    /**
     * Height of the image in pixels
     * @type {number}
     * @memberof ImageDTO
     */
    height?: number;
    /**
     * Display order for sorting images
     * @type {number}
     * @memberof ImageDTO
     */
    displayOrder?: number;
}

/**
 * Check if a given object implements the ImageDTO interface.
 */
export function instanceOfImageDTO(value: object): value is ImageDTO {
    return true;
}

export function ImageDTOFromJSON(json: any): ImageDTO {
    return ImageDTOFromJSONTyped(json, false);
}

export function ImageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'displayOrder': json['displayOrder'] == null ? undefined : json['displayOrder'],
    };
}

export function ImageDTOToJSON(json: any): ImageDTO {
    return ImageDTOToJSONTyped(json, false);
}

export function ImageDTOToJSONTyped(value?: ImageDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'width': value['width'],
        'height': value['height'],
        'displayOrder': value['displayOrder'],
    };
}

