/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei API
 * API documentation for Sunrei project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SunreiDTO } from './SunreiDTO';
import {
    SunreiDTOFromJSON,
    SunreiDTOFromJSONTyped,
    SunreiDTOToJSON,
    SunreiDTOToJSONTyped,
} from './SunreiDTO';

/**
 * 
 * @export
 * @interface ListSunreiResult
 */
export interface ListSunreiResult {
    /**
     * List of Sunrei within the polygon area
     * @type {Array<SunreiDTO>}
     * @memberof ListSunreiResult
     */
    sunreis?: Array<SunreiDTO>;
    /**
     * Total number of Sunrei found
     * @type {number}
     * @memberof ListSunreiResult
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the ListSunreiResult interface.
 */
export function instanceOfListSunreiResult(value: object): value is ListSunreiResult {
    return true;
}

export function ListSunreiResultFromJSON(json: any): ListSunreiResult {
    return ListSunreiResultFromJSONTyped(json, false);
}

export function ListSunreiResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSunreiResult {
    if (json == null) {
        return json;
    }
    return {
        
        'sunreis': json['sunreis'] == null ? undefined : ((json['sunreis'] as Array<any>).map(SunreiDTOFromJSON)),
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function ListSunreiResultToJSON(json: any): ListSunreiResult {
    return ListSunreiResultToJSONTyped(json, false);
}

export function ListSunreiResultToJSONTyped(value?: ListSunreiResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sunreis': value['sunreis'] == null ? undefined : ((value['sunreis'] as Array<any>).map(SunreiDTOToJSON)),
        'totalCount': value['totalCount'],
    };
}

