/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei API
 * API documentation for Sunrei project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Coordinate } from './Coordinate';
import {
    CoordinateFromJSON,
    CoordinateFromJSONTyped,
    CoordinateToJSON,
    CoordinateToJSONTyped,
} from './Coordinate';

/**
 * 
 * @export
 * @interface ListSunreiParams
 */
export interface ListSunreiParams {
    /**
     * Array of coordinates forming a polygon (minimum 3 points)
     * @type {Array<Coordinate>}
     * @memberof ListSunreiParams
     */
    polygon: Array<Coordinate>;
}

/**
 * Check if a given object implements the ListSunreiParams interface.
 */
export function instanceOfListSunreiParams(value: object): value is ListSunreiParams {
    if (!('polygon' in value) || value['polygon'] === undefined) return false;
    return true;
}

export function ListSunreiParamsFromJSON(json: any): ListSunreiParams {
    return ListSunreiParamsFromJSONTyped(json, false);
}

export function ListSunreiParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSunreiParams {
    if (json == null) {
        return json;
    }
    return {
        
        'polygon': ((json['polygon'] as Array<any>).map(CoordinateFromJSON)),
    };
}

export function ListSunreiParamsToJSON(json: any): ListSunreiParams {
    return ListSunreiParamsToJSONTyped(json, false);
}

export function ListSunreiParamsToJSONTyped(value?: ListSunreiParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'polygon': ((value['polygon'] as Array<any>).map(CoordinateToJSON)),
    };
}

