/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei API
 * API documentation for Sunrei project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceDTO
 */
export interface PlaceDTO {
    /**
     * 
     * @type {string}
     * @memberof PlaceDTO
     */
    id?: string;
    /**
     * Name of the place
     * @type {string}
     * @memberof PlaceDTO
     */
    name?: string;
    /**
     * Address of the place
     * @type {string}
     * @memberof PlaceDTO
     */
    address?: string;
    /**
     * Latitude of the place
     * @type {number}
     * @memberof PlaceDTO
     */
    latitude?: number;
    /**
     * Longitude of the place
     * @type {number}
     * @memberof PlaceDTO
     */
    longitude?: number;
}

/**
 * Check if a given object implements the PlaceDTO interface.
 */
export function instanceOfPlaceDTO(value: object): value is PlaceDTO {
    return true;
}

export function PlaceDTOFromJSON(json: any): PlaceDTO {
    return PlaceDTOFromJSONTyped(json, false);
}

export function PlaceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
    };
}

export function PlaceDTOToJSON(json: any): PlaceDTO {
    return PlaceDTOToJSONTyped(json, false);
}

export function PlaceDTOToJSONTyped(value?: PlaceDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

