/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei API
 * API documentation for Sunrei project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageDTO } from './ImageDTO';
import {
    ImageDTOFromJSON,
    ImageDTOFromJSONTyped,
    ImageDTOToJSON,
    ImageDTOToJSONTyped,
} from './ImageDTO';
import type { PlaceDTO } from './PlaceDTO';
import {
    PlaceDTOFromJSON,
    PlaceDTOFromJSONTyped,
    PlaceDTOToJSON,
    PlaceDTOToJSONTyped,
} from './PlaceDTO';

/**
 * 
 * @export
 * @interface SunreiSpotDTO
 */
export interface SunreiSpotDTO {
    /**
     * 
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    id?: string;
    /**
     * Title of the Sunrei Spot
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    title?: string;
    /**
     * Detailed description of the Sunrei Spot
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    description?: string;
    /**
     * YouTube video link for this spot
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    youtubeLink?: string | null;
    /**
     * Array of images for this spot
     * @type {Array<ImageDTO>}
     * @memberof SunreiSpotDTO
     */
    images?: Array<ImageDTO>;
    /**
     * Foreign key to the associated Place
     * @type {Array<PlaceDTO>}
     * @memberof SunreiSpotDTO
     */
    places?: Array<PlaceDTO>;
}

/**
 * Check if a given object implements the SunreiSpotDTO interface.
 */
export function instanceOfSunreiSpotDTO(value: object): value is SunreiSpotDTO {
    return true;
}

export function SunreiSpotDTOFromJSON(json: any): SunreiSpotDTO {
    return SunreiSpotDTOFromJSONTyped(json, false);
}

export function SunreiSpotDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SunreiSpotDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'youtubeLink': json['youtubeLink'] == null ? undefined : json['youtubeLink'],
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ImageDTOFromJSON)),
        'places': json['places'] == null ? undefined : ((json['places'] as Array<any>).map(PlaceDTOFromJSON)),
    };
}

export function SunreiSpotDTOToJSON(json: any): SunreiSpotDTO {
    return SunreiSpotDTOToJSONTyped(json, false);
}

export function SunreiSpotDTOToJSONTyped(value?: SunreiSpotDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'youtubeLink': value['youtubeLink'],
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImageDTOToJSON)),
        'places': value['places'] == null ? undefined : ((value['places'] as Array<any>).map(PlaceDTOToJSON)),
    };
}

