/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei API
 * API documentation for Sunrei project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagDTO
 */
export interface TagDTO {
    /**
     * 
     * @type {string}
     * @memberof TagDTO
     */
    id?: string;
    /**
     * Name of the tag
     * @type {string}
     * @memberof TagDTO
     */
    name?: string;
    /**
     * Description of the tag
     * @type {string}
     * @memberof TagDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the TagDTO interface.
 */
export function instanceOfTagDTO(value: object): value is TagDTO {
    return true;
}

export function TagDTOFromJSON(json: any): TagDTO {
    return TagDTOFromJSONTyped(json, false);
}

export function TagDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function TagDTOToJSON(json: any): TagDTO {
    return TagDTOToJSONTyped(json, false);
}

export function TagDTOToJSONTyped(value?: TagDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

