services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: sunrei
      POSTGRES_USER: sunrei
      POSTGRES_PASSWORD: sunrei
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sunrei -d sunrei"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:10-alpine
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    command: -url=jdbc:postgresql://postgres_container:5432/sunrei -user=sunrei -password=sunrei -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql

volumes:
  postgres_data:
