version: '3.8'

services:
  postgres:
    image: ghcr.io/yongseongkim/homelab-infra/postgres18-postgis:latest
    container_name: sunrei-postgres
    platform: linux/arm64
    environment:
      POSTGRES_DB: sunrei
      POSTGRES_USER: sunrei
      POSTGRES_PASSWORD: sunrei
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    driver: local
