/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei Admin API
 * Admin API for Sunrei content management (Source -> Sunrei -> SunreiSpot -> Place).
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CreateSourceRequest {
    'type': SourceType;
    'name': string;
    'nameEn'?: string | null;
    'nameKo'?: string | null;
    'synopsis'?: string | null;
    'externalUrl'?: string | null;
    'posterImage'?: MultiSizeImageDTO | null;
}


export interface CreateSunreiRequest {
    'sourceId': string;
    /**
     * true -> published_at = now() (preserved on re-save); false -> NULL (draft).
     */
    'published': boolean;
    'title': string;
    'summary'?: string | null;
    'description'?: string | null;
    'link'?: string | null;
    'images'?: Array<MultiSizeImageDTO>;
    'spots'?: Array<CreateSunreiSpotInline>;
}
export interface CreateSunreiSpotInline {
    'title': string;
    'description'?: string | null;
    'context'?: string | null;
    'youtubeLink'?: string | null;
    'place'?: PlaceInput | null;
    'images'?: Array<MultiSizeImageDTO>;
    /**
     * Existing tag IDs to attach to this spot.
     */
    'tagIds'?: Array<string>;
    /**
     * KO labels to find-or-create and attach (ko=typed, en=typed until translated).
     */
    'tagLabels'?: Array<string>;
}
export interface CreateTagRequest {
    'labelEn': string;
    'labelKo': string;
    'description'?: string | null;
}
export interface ImageDTO {
    'url': string;
    'width'?: number;
    'height'?: number;
}
export interface ImageInput {
    'url': string;
    'width'?: number;
    'height'?: number;
}
export interface ListPlacesResult {
    'data': Array<PlaceListItemDTO>;
    'totalSize': number;
    'totalElements': number;
    'nextToken'?: string | null;
}
export interface ListSourcesResult {
    'data': Array<SourceRowDTO>;
    'totalSize': number;
    'totalElements': number;
    'nextToken'?: string | null;
}
export interface ListSunreisResult {
    'data': Array<SunreiDTO>;
    'totalSize': number;
    'totalElements': number;
    'nextToken'?: string | null;
}
export interface ListTagsResult {
    'data': Array<TagDTO>;
    'totalSize': number;
    'totalElements': number;
    'nextToken'?: string | null;
    /**
     * Map of tag ID to number of associated SunreiSpots
     */
    'spotCountByTagId'?: { [key: string]: number; };
}
export interface LoginRequest {
    'username': string;
    'password': string;
}
export interface LoginResponse {
    'token': string;
    'expiresIn': number;
    'user': LoginResponseUser;
}
export interface LoginResponseUser {
    'id': string;
    'username': string;
    'role': string;
}
export interface MultiSizeImageDTO {
    'images': Array<ImageDTO>;
}
export interface PlaceDTO {
    'id': string;
    'name': string;
    'address'?: string | null;
    'latitude': number;
    'longitude': number;
    'googleMapsId'?: string | null;
    'isClosed': boolean;
    'closedReason'?: string | null;
    'closedAt'?: string | null;
    'notes'?: string | null;
}
export interface PlaceInput {
    /**
     * ID for existing place (omit to create new)
     */
    'id'?: string;
    'name': string;
    'address': string;
    'latitude': number;
    'longitude': number;
    /**
     * Google Maps Place ID (dedupe key)
     */
    'googleMapsId'?: string | null;
}
export interface PlaceListItemDTO {
    'id': string;
    'name': string;
    'address'?: string | null;
    'latitude': number;
    'longitude': number;
    'googleMapsId'?: string | null;
    'isClosed': boolean;
    /**
     * Area label (KO), derived from address.
     */
    'area'?: string | null;
    'sourceCount': number;
    'spotCount': number;
}
export interface SourceDTO {
    'id': string;
    'type': SourceType;
    'name': string;
    'nameEn'?: string | null;
    'nameKo'?: string | null;
    'synopsis'?: string | null;
    'externalUrl'?: string | null;
    'posterImage'?: MultiSizeImageDTO | null;
    'createdAt'?: string;
    'updatedAt'?: string;
}


/**
 * Source list row with counts (app-behavior text is derived client-side from type).
 */
export interface SourceRowDTO {
    'id': string;
    'type': SourceType;
    'name': string;
    'nameEn'?: string | null;
    'nameKo'?: string | null;
    'synopsis'?: string | null;
    'externalUrl'?: string | null;
    'posterImage'?: MultiSizeImageDTO | null;
    'createdAt'?: string;
    'updatedAt'?: string;
    'sunreiCount'?: number;
    'spotCount'?: number;
}



export const SourceType = {
    Youtube: 'YOUTUBE',
    Tv: 'TV',
    Anime: 'ANIME',
    Other: 'OTHER'
} as const;

export type SourceType = typeof SourceType[keyof typeof SourceType];


export interface SpotSummaryDTO {
    'id': string;
    'title': string;
    'sunreiId': string;
    'sunreiTitle': string;
}
export interface SunreiDTO {
    'id': string;
    'sourceId': string;
    'source': SourceDTO;
    /**
     * NULL = draft; set = published
     */
    'publishedAt'?: string | null;
    'title': string;
    'description'?: string | null;
    'summary'?: string | null;
    'link'?: string | null;
    'images': Array<MultiSizeImageDTO>;
    'spots': Array<SunreiSpotDTO>;
    'createdAt'?: string;
    'updatedAt'?: string;
}
export interface SunreiSpotDTO {
    'id': string;
    'sunreiId': string;
    'title': string;
    'description'?: string | null;
    /**
     * What this source says here.
     */
    'context'?: string | null;
    'youtubeLink'?: string | null;
    'images': Array<MultiSizeImageDTO>;
    'place': PlaceDTO;
    'tags': Array<TagDTO>;
}
export interface TagDTO {
    'id': string;
    'labelEn': string;
    'labelKo': string;
    'description'?: string | null;
}
export interface TagWithSpots {
    'id': string;
    'labelEn': string;
    'labelKo': string;
    'description'?: string | null;
    'spots': Array<SpotSummaryDTO>;
}
export interface UpdateSourceRequest {
    'type'?: SourceType;
    'name'?: string | null;
    'nameEn'?: string | null;
    'nameKo'?: string | null;
    'synopsis'?: string | null;
    'externalUrl'?: string | null;
    'posterImage'?: MultiSizeImageDTO | null;
}


export interface UpdateSunreiRequest {
    'sourceId'?: string | null;
    'published'?: boolean | null;
    'title'?: string | null;
    'summary'?: string | null;
    'description'?: string | null;
    'link'?: string | null;
    'images'?: Array<MultiSizeImageDTO> | null;
    'spots'?: Array<UpdateSunreiSpotInline>;
}
export interface UpdateSunreiSpotInline {
    /**
     * ID for existing spot (omit for new spots)
     */
    'id'?: string;
    'title': string;
    'description'?: string | null;
    'context'?: string | null;
    'youtubeLink'?: string | null;
    'place'?: PlaceInput | null;
    'images'?: Array<MultiSizeImageDTO> | null;
    /**
     * Replaces this spot\'s tags when present.
     */
    'tagIds'?: Array<string> | null;
    /**
     * KO labels to find-or-create and attach.
     */
    'tagLabels'?: Array<string> | null;
    /**
     * Mark this spot for deletion
     */
    '_delete'?: boolean;
}
export interface UpdateTagRequest {
    'labelEn'?: string | null;
    'labelKo'?: string | null;
    'description'?: string | null;
}
export interface UploadImageFromUrlRequest {
    'url': string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create source
         * @param {CreateSourceRequest} createSourceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSource: async (createSourceRequest: CreateSourceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSourceRequest' is not null or undefined
            assertParamExists('createSource', 'createSourceRequest', createSourceRequest)
            const localVarPath = `/admin/sources`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSourceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create new Sunrei
         * @param {CreateSunreiRequest} createSunreiRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSunrei: async (createSunreiRequest: CreateSunreiRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSunreiRequest' is not null or undefined
            assertParamExists('createSunrei', 'createSunreiRequest', createSunreiRequest)
            const localVarPath = `/admin/sunreis`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSunreiRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create new bilingual tag
         * @param {CreateTagRequest} createTagRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTag: async (createTagRequest: CreateTagRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createTagRequest' is not null or undefined
            assertParamExists('createTag', 'createTagRequest', createTagRequest)
            const localVarPath = `/admin/tags`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTagRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Soft-delete source
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSource: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteSource', 'id', id)
            const localVarPath = `/admin/sources/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Sunrei
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSunrei: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteSunrei', 'id', id)
            const localVarPath = `/admin/sunreis/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete tag
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTag: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteTag', 'id', id)
            const localVarPath = `/admin/tags/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Detach a spot from a tag
         * @param {string} id Tag ID
         * @param {string} spotId SunreiSpot ID to detach
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        detachSpotFromTag: async (id: string, spotId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('detachSpotFromTag', 'id', id)
            // verify required parameter 'spotId' is not null or undefined
            assertParamExists('detachSpotFromTag', 'spotId', spotId)
            const localVarPath = `/admin/tags/{id}/spots/{spotId}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"spotId"}}`, encodeURIComponent(String(spotId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get source
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSource: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSource', 'id', id)
            const localVarPath = `/admin/sources/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Sunrei details
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSunrei: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSunrei', 'id', id)
            const localVarPath = `/admin/sunreis/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get tag with associated spots
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTag: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTag', 'id', id)
            const localVarPath = `/admin/tags/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List places (keyed by Google place_id; Area/Sources/Spots columns)
         * @param {string} [q] 
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlaces: async (q?: string, nextToken?: string, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/places`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (nextToken !== undefined) {
                localVarQueryParameter['nextToken'] = nextToken;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List sources
         * @param {string} [q] 
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSources: async (q?: string, nextToken?: string, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/sources`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (nextToken !== undefined) {
                localVarQueryParameter['nextToken'] = nextToken;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Sunreis with pagination
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {string} [q] 
         * @param {string} [sourceId] 
         * @param {boolean} [published] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSunreis: async (nextToken?: string, size?: number, q?: string, sourceId?: string, published?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/sunreis`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (nextToken !== undefined) {
                localVarQueryParameter['nextToken'] = nextToken;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (sourceId !== undefined) {
                localVarQueryParameter['sourceId'] = sourceId;
            }

            if (published !== undefined) {
                localVarQueryParameter['published'] = published;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List tags with pagination
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTags: async (nextToken?: string, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/tags`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (nextToken !== undefined) {
                localVarQueryParameter['nextToken'] = nextToken;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Admin login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/admin/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search tags by label (en or ko)
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchTags: async (q: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('searchTags', 'q', q)
            const localVarPath = `/admin/tags/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update source
         * @param {string} id 
         * @param {UpdateSourceRequest} updateSourceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSource: async (id: string, updateSourceRequest: UpdateSourceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateSource', 'id', id)
            // verify required parameter 'updateSourceRequest' is not null or undefined
            assertParamExists('updateSource', 'updateSourceRequest', updateSourceRequest)
            const localVarPath = `/admin/sources/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSourceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Sunrei
         * @param {string} id 
         * @param {UpdateSunreiRequest} updateSunreiRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSunrei: async (id: string, updateSunreiRequest: UpdateSunreiRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateSunrei', 'id', id)
            // verify required parameter 'updateSunreiRequest' is not null or undefined
            assertParamExists('updateSunrei', 'updateSunreiRequest', updateSunreiRequest)
            const localVarPath = `/admin/sunreis/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSunreiRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update tag labels
         * @param {string} id 
         * @param {UpdateTagRequest} updateTagRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTag: async (id: string, updateTagRequest: UpdateTagRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateTag', 'id', id)
            // verify required parameter 'updateTagRequest' is not null or undefined
            assertParamExists('updateTag', 'updateTagRequest', updateTagRequest)
            const localVarPath = `/admin/tags/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateTagRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload image
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImage: async (file: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadImage', 'file', file)
            const localVarPath = `/admin/images/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload image from URL
         * @param {UploadImageFromUrlRequest} uploadImageFromUrlRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImageFromUrl: async (uploadImageFromUrlRequest: UploadImageFromUrlRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uploadImageFromUrlRequest' is not null or undefined
            assertParamExists('uploadImageFromUrl', 'uploadImageFromUrlRequest', uploadImageFromUrlRequest)
            const localVarPath = `/admin/images/upload-url`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(uploadImageFromUrlRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create source
         * @param {CreateSourceRequest} createSourceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSource(createSourceRequest: CreateSourceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SourceDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSource(createSourceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createSource']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create new Sunrei
         * @param {CreateSunreiRequest} createSunreiRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSunrei(createSunreiRequest: CreateSunreiRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SunreiDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSunrei(createSunreiRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createSunrei']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create new bilingual tag
         * @param {CreateTagRequest} createTagRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTag(createTagRequest: CreateTagRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TagDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTag(createTagRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createTag']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Soft-delete source
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSource(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSource(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteSource']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Sunrei
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSunrei(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSunrei(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteSunrei']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete tag
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTag(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTag(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteTag']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Detach a spot from a tag
         * @param {string} id Tag ID
         * @param {string} spotId SunreiSpot ID to detach
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async detachSpotFromTag(id: string, spotId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.detachSpotFromTag(id, spotId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.detachSpotFromTag']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get source
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSource(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SourceDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSource(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSource']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Sunrei details
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSunrei(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SunreiDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSunrei(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSunrei']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get tag with associated spots
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTag(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TagWithSpots>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTag(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getTag']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List places (keyed by Google place_id; Area/Sources/Spots columns)
         * @param {string} [q] 
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPlaces(q?: string, nextToken?: string, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPlacesResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPlaces(q, nextToken, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listPlaces']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List sources
         * @param {string} [q] 
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSources(q?: string, nextToken?: string, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSourcesResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSources(q, nextToken, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listSources']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Sunreis with pagination
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {string} [q] 
         * @param {string} [sourceId] 
         * @param {boolean} [published] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSunreis(nextToken?: string, size?: number, q?: string, sourceId?: string, published?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSunreisResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSunreis(nextToken, size, q, sourceId, published, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listSunreis']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List tags with pagination
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTags(nextToken?: string, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTagsResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTags(nextToken, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listTags']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Admin login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search tags by label (en or ko)
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchTags(q: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TagDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchTags(q, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.searchTags']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update source
         * @param {string} id 
         * @param {UpdateSourceRequest} updateSourceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSource(id: string, updateSourceRequest: UpdateSourceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SourceDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSource(id, updateSourceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateSource']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Sunrei
         * @param {string} id 
         * @param {UpdateSunreiRequest} updateSunreiRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSunrei(id: string, updateSunreiRequest: UpdateSunreiRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SunreiDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSunrei(id, updateSunreiRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateSunrei']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update tag labels
         * @param {string} id 
         * @param {UpdateTagRequest} updateTagRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTag(id: string, updateTagRequest: UpdateTagRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TagDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTag(id, updateTagRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateTag']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upload image
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadImage(file: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MultiSizeImageDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadImage(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.uploadImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upload image from URL
         * @param {UploadImageFromUrlRequest} uploadImageFromUrlRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadImageFromUrl(uploadImageFromUrlRequest: UploadImageFromUrlRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MultiSizeImageDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadImageFromUrl(uploadImageFromUrlRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.uploadImageFromUrl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Create source
         * @param {CreateSourceRequest} createSourceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSource(createSourceRequest: CreateSourceRequest, options?: RawAxiosRequestConfig): AxiosPromise<SourceDTO> {
            return localVarFp.createSource(createSourceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create new Sunrei
         * @param {CreateSunreiRequest} createSunreiRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSunrei(createSunreiRequest: CreateSunreiRequest, options?: RawAxiosRequestConfig): AxiosPromise<SunreiDTO> {
            return localVarFp.createSunrei(createSunreiRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create new bilingual tag
         * @param {CreateTagRequest} createTagRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTag(createTagRequest: CreateTagRequest, options?: RawAxiosRequestConfig): AxiosPromise<TagDTO> {
            return localVarFp.createTag(createTagRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Soft-delete source
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSource(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSource(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Sunrei
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSunrei(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSunrei(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete tag
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTag(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTag(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Detach a spot from a tag
         * @param {string} id Tag ID
         * @param {string} spotId SunreiSpot ID to detach
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        detachSpotFromTag(id: string, spotId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.detachSpotFromTag(id, spotId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get source
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSource(id: string, options?: RawAxiosRequestConfig): AxiosPromise<SourceDTO> {
            return localVarFp.getSource(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Sunrei details
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSunrei(id: string, options?: RawAxiosRequestConfig): AxiosPromise<SunreiDTO> {
            return localVarFp.getSunrei(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get tag with associated spots
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTag(id: string, options?: RawAxiosRequestConfig): AxiosPromise<TagWithSpots> {
            return localVarFp.getTag(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List places (keyed by Google place_id; Area/Sources/Spots columns)
         * @param {string} [q] 
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlaces(q?: string, nextToken?: string, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<ListPlacesResult> {
            return localVarFp.listPlaces(q, nextToken, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List sources
         * @param {string} [q] 
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSources(q?: string, nextToken?: string, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<ListSourcesResult> {
            return localVarFp.listSources(q, nextToken, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Sunreis with pagination
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {string} [q] 
         * @param {string} [sourceId] 
         * @param {boolean} [published] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSunreis(nextToken?: string, size?: number, q?: string, sourceId?: string, published?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<ListSunreisResult> {
            return localVarFp.listSunreis(nextToken, size, q, sourceId, published, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List tags with pagination
         * @param {string} [nextToken] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTags(nextToken?: string, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<ListTagsResult> {
            return localVarFp.listTags(nextToken, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Admin login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.login(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search tags by label (en or ko)
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchTags(q: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<TagDTO>> {
            return localVarFp.searchTags(q, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update source
         * @param {string} id 
         * @param {UpdateSourceRequest} updateSourceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSource(id: string, updateSourceRequest: UpdateSourceRequest, options?: RawAxiosRequestConfig): AxiosPromise<SourceDTO> {
            return localVarFp.updateSource(id, updateSourceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Sunrei
         * @param {string} id 
         * @param {UpdateSunreiRequest} updateSunreiRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSunrei(id: string, updateSunreiRequest: UpdateSunreiRequest, options?: RawAxiosRequestConfig): AxiosPromise<SunreiDTO> {
            return localVarFp.updateSunrei(id, updateSunreiRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update tag labels
         * @param {string} id 
         * @param {UpdateTagRequest} updateTagRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTag(id: string, updateTagRequest: UpdateTagRequest, options?: RawAxiosRequestConfig): AxiosPromise<TagDTO> {
            return localVarFp.updateTag(id, updateTagRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload image
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImage(file: File, options?: RawAxiosRequestConfig): AxiosPromise<MultiSizeImageDTO> {
            return localVarFp.uploadImage(file, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload image from URL
         * @param {UploadImageFromUrlRequest} uploadImageFromUrlRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImageFromUrl(uploadImageFromUrlRequest: UploadImageFromUrlRequest, options?: RawAxiosRequestConfig): AxiosPromise<MultiSizeImageDTO> {
            return localVarFp.uploadImageFromUrl(uploadImageFromUrlRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Create source
     * @param {CreateSourceRequest} createSourceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSource(createSourceRequest: CreateSourceRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createSource(createSourceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create new Sunrei
     * @param {CreateSunreiRequest} createSunreiRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSunrei(createSunreiRequest: CreateSunreiRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createSunrei(createSunreiRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create new bilingual tag
     * @param {CreateTagRequest} createTagRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTag(createTagRequest: CreateTagRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createTag(createTagRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Soft-delete source
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSource(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteSource(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Sunrei
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSunrei(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteSunrei(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete tag
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTag(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteTag(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Detach a spot from a tag
     * @param {string} id Tag ID
     * @param {string} spotId SunreiSpot ID to detach
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public detachSpotFromTag(id: string, spotId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).detachSpotFromTag(id, spotId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get source
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSource(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSource(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Sunrei details
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSunrei(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSunrei(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get tag with associated spots
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTag(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTag(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List places (keyed by Google place_id; Area/Sources/Spots columns)
     * @param {string} [q] 
     * @param {string} [nextToken] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listPlaces(q?: string, nextToken?: string, size?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listPlaces(q, nextToken, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List sources
     * @param {string} [q] 
     * @param {string} [nextToken] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listSources(q?: string, nextToken?: string, size?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listSources(q, nextToken, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Sunreis with pagination
     * @param {string} [nextToken] 
     * @param {number} [size] 
     * @param {string} [q] 
     * @param {string} [sourceId] 
     * @param {boolean} [published] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listSunreis(nextToken?: string, size?: number, q?: string, sourceId?: string, published?: boolean, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listSunreis(nextToken, size, q, sourceId, published, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List tags with pagination
     * @param {string} [nextToken] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTags(nextToken?: string, size?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listTags(nextToken, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Admin login
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).login(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search tags by label (en or ko)
     * @param {string} q 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchTags(q: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).searchTags(q, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update source
     * @param {string} id 
     * @param {UpdateSourceRequest} updateSourceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateSource(id: string, updateSourceRequest: UpdateSourceRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateSource(id, updateSourceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Sunrei
     * @param {string} id 
     * @param {UpdateSunreiRequest} updateSunreiRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateSunrei(id: string, updateSunreiRequest: UpdateSunreiRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateSunrei(id, updateSunreiRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update tag labels
     * @param {string} id 
     * @param {UpdateTagRequest} updateTagRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateTag(id: string, updateTagRequest: UpdateTagRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateTag(id, updateTagRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload image
     * @param {File} file 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadImage(file: File, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).uploadImage(file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload image from URL
     * @param {UploadImageFromUrlRequest} uploadImageFromUrlRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadImageFromUrl(uploadImageFromUrlRequest: UploadImageFromUrlRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).uploadImageFromUrl(uploadImageFromUrlRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



