/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei API
 * API documentation for Sunrei project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Coordinate
 */
export interface Coordinate {
    /**
     * Latitude coordinate
     * @type {number}
     * @memberof Coordinate
     */
    'lat': number;
    /**
     * Longitude coordinate
     * @type {number}
     * @memberof Coordinate
     */
    'lng': number;
}
/**
 * 
 * @export
 * @interface GetSunreiParams
 */
export interface GetSunreiParams {
    /**
     * ID of the Sunrei to retrieve
     * @type {number}
     * @memberof GetSunreiParams
     */
    'id'?: number;
}
/**
 * 
 * @export
 * @interface GetSunreiResult
 */
export interface GetSunreiResult {
    /**
     * 
     * @type {SunreiDTO}
     * @memberof GetSunreiResult
     */
    'sunrei'?: SunreiDTO;
}
/**
 * 
 * @export
 * @interface ListSunreiParams
 */
export interface ListSunreiParams {
    /**
     * Array of coordinates forming a polygon (minimum 3 points)
     * @type {Array<Coordinate>}
     * @memberof ListSunreiParams
     */
    'polygon': Array<Coordinate>;
}
/**
 * 
 * @export
 * @interface ListSunreiResult
 */
export interface ListSunreiResult {
    /**
     * List of Sunrei within the polygon area
     * @type {Array<SunreiDTO>}
     * @memberof ListSunreiResult
     */
    'sunreis'?: Array<SunreiDTO>;
    /**
     * Total number of Sunrei found
     * @type {number}
     * @memberof ListSunreiResult
     */
    'totalCount'?: number;
}
/**
 * 
 * @export
 * @interface PlaceDTO
 */
export interface PlaceDTO {
    /**
     * 
     * @type {string}
     * @memberof PlaceDTO
     */
    'id'?: string;
    /**
     * Name of the place
     * @type {string}
     * @memberof PlaceDTO
     */
    'name'?: string;
    /**
     * Address of the place
     * @type {string}
     * @memberof PlaceDTO
     */
    'address'?: string;
    /**
     * Latitude of the place
     * @type {number}
     * @memberof PlaceDTO
     */
    'latitude'?: number;
    /**
     * Longitude of the place
     * @type {number}
     * @memberof PlaceDTO
     */
    'longitude'?: number;
}
/**
 * 
 * @export
 * @interface SunreiDTO
 */
export interface SunreiDTO {
    /**
     * 
     * @type {string}
     * @memberof SunreiDTO
     */
    'id'?: string;
    /**
     * Title of the Sunrei Spot
     * @type {string}
     * @memberof SunreiDTO
     */
    'title'?: string;
    /**
     * Detailed description of the Sunrei Spot
     * @type {string}
     * @memberof SunreiDTO
     */
    'description'?: string;
    /**
     * Foreign key to the associated Place
     * @type {Array<SunreiSpotDTO>}
     * @memberof SunreiDTO
     */
    'spots'?: Array<SunreiSpotDTO>;
}
/**
 * 
 * @export
 * @interface SunreiSpotDTO
 */
export interface SunreiSpotDTO {
    /**
     * 
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'id'?: string;
    /**
     * Title of the Sunrei Spot
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'title'?: string;
    /**
     * Detailed description of the Sunrei Spot
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'description'?: string;
    /**
     * Foreign key to the associated Place
     * @type {Array<PlaceDTO>}
     * @memberof SunreiSpotDTO
     */
    'places'?: Array<PlaceDTO>;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List Sunrei Spots with filters
         * @param {number} lat 
         * @param {number} lng 
         * @param {number} radius 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sunreiSpotsGet: async (lat: number, lng: number, radius: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'lat' is not null or undefined
            assertParamExists('sunreiSpotsGet', 'lat', lat)
            // verify required parameter 'lng' is not null or undefined
            assertParamExists('sunreiSpotsGet', 'lng', lng)
            // verify required parameter 'radius' is not null or undefined
            assertParamExists('sunreiSpotsGet', 'radius', radius)
            const localVarPath = `/sunrei-spots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (lat !== undefined) {
                localVarQueryParameter['lat'] = lat;
            }

            if (lng !== undefined) {
                localVarQueryParameter['lng'] = lng;
            }

            if (radius !== undefined) {
                localVarQueryParameter['radius'] = radius;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Sunrei with optional polygon filter
         * @param {string} [polygon] JSON string of coordinate array forming a polygon to filter results (e.g., \&quot;[[35.6762,139.6503],[35.6795,139.7005],[35.6585,139.7454]]\&quot;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sunreisGet: async (polygon?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/sunreis`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (polygon !== undefined) {
                localVarQueryParameter['polygon'] = polygon;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Sunrei by ID
         * @param {string} id ID of the Sunrei to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sunreisIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sunreisIdGet', 'id', id)
            const localVarPath = `/sunreis/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List Sunrei Spots with filters
         * @param {number} lat 
         * @param {number} lng 
         * @param {number} radius 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sunreiSpotsGet(lat: number, lng: number, radius: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SunreiSpotDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sunreiSpotsGet(lat, lng, radius, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.sunreiSpotsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Sunrei with optional polygon filter
         * @param {string} [polygon] JSON string of coordinate array forming a polygon to filter results (e.g., \&quot;[[35.6762,139.6503],[35.6795,139.7005],[35.6585,139.7454]]\&quot;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sunreisGet(polygon?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSunreiResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sunreisGet(polygon, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.sunreisGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Sunrei by ID
         * @param {string} id ID of the Sunrei to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sunreisIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSunreiResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sunreisIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.sunreisIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary List Sunrei Spots with filters
         * @param {number} lat 
         * @param {number} lng 
         * @param {number} radius 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sunreiSpotsGet(lat: number, lng: number, radius: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<SunreiSpotDTO>> {
            return localVarFp.sunreiSpotsGet(lat, lng, radius, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Sunrei with optional polygon filter
         * @param {string} [polygon] JSON string of coordinate array forming a polygon to filter results (e.g., \&quot;[[35.6762,139.6503],[35.6795,139.7005],[35.6585,139.7454]]\&quot;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sunreisGet(polygon?: string, options?: RawAxiosRequestConfig): AxiosPromise<ListSunreiResult> {
            return localVarFp.sunreisGet(polygon, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Sunrei by ID
         * @param {string} id ID of the Sunrei to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sunreisIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<GetSunreiResult> {
            return localVarFp.sunreisIdGet(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary List Sunrei Spots with filters
     * @param {number} lat 
     * @param {number} lng 
     * @param {number} radius 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public sunreiSpotsGet(lat: number, lng: number, radius: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).sunreiSpotsGet(lat, lng, radius, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Sunrei with optional polygon filter
     * @param {string} [polygon] JSON string of coordinate array forming a polygon to filter results (e.g., \&quot;[[35.6762,139.6503],[35.6795,139.7005],[35.6585,139.7454]]\&quot;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public sunreisGet(polygon?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).sunreisGet(polygon, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Sunrei by ID
     * @param {string} id ID of the Sunrei to retrieve
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public sunreisIdGet(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).sunreisIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
}



