/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei App API
 * Public API for Sunrei client applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Coordinate
 */
export interface Coordinate {
    /**
     * Latitude coordinate
     * @type {number}
     * @memberof Coordinate
     */
    'lat': number;
    /**
     * Longitude coordinate
     * @type {number}
     * @memberof Coordinate
     */
    'lng': number;
}
/**
 * 
 * @export
 * @interface GetSunreiResult
 */
export interface GetSunreiResult {
    /**
     * 
     * @type {SunreiDTO}
     * @memberof GetSunreiResult
     */
    'sunrei': SunreiDTO;
}
/**
 * 
 * @export
 * @interface ImageDTO
 */
export interface ImageDTO {
    /**
     * URL of the image
     * @type {string}
     * @memberof ImageDTO
     */
    'url': string;
    /**
     * Width of the image in pixels
     * @type {number}
     * @memberof ImageDTO
     */
    'width'?: number;
    /**
     * Height of the image in pixels
     * @type {number}
     * @memberof ImageDTO
     */
    'height'?: number;
}
/**
 * 
 * @export
 * @interface ListMapSpots
 */
export interface ListMapSpots {
    /**
     * List of spots with embedded Sunrei info for map display
     * @type {Array<MapSunreiSpotDTO>}
     * @memberof ListMapSpots
     */
    'spots': Array<MapSunreiSpotDTO>;
}
/**
 * 
 * @export
 * @interface ListSunreiResult
 */
export interface ListSunreiResult {
    /**
     * List of Sunrei
     * @type {Array<SunreiDTO>}
     * @memberof ListSunreiResult
     */
    'sunreis': Array<SunreiDTO>;
    /**
     * Total number of Sunrei found
     * @type {number}
     * @memberof ListSunreiResult
     */
    'totalCount': number;
}
/**
 * 
 * @export
 * @interface MapSunreiSpotDTO
 */
export interface MapSunreiSpotDTO {
    /**
     * 
     * @type {string}
     * @memberof MapSunreiSpotDTO
     */
    'id': string;
    /**
     * ID of the parent Sunrei
     * @type {string}
     * @memberof MapSunreiSpotDTO
     */
    'sunreiId': string;
    /**
     * Title of the Sunrei Spot
     * @type {string}
     * @memberof MapSunreiSpotDTO
     */
    'title': string;
    /**
     * Detailed description of the Sunrei Spot
     * @type {string}
     * @memberof MapSunreiSpotDTO
     */
    'description'?: string;
    /**
     * YouTube video link for this spot
     * @type {string}
     * @memberof MapSunreiSpotDTO
     */
    'youtubeLink'?: string | null;
    /**
     * Array of multi-size images for this spot
     * @type {Array<MultiSizeImageDTO>}
     * @memberof MapSunreiSpotDTO
     */
    'images': Array<MultiSizeImageDTO>;
    /**
     * 
     * @type {PlaceDTO}
     * @memberof MapSunreiSpotDTO
     */
    'place': PlaceDTO;
    /**
     * 
     * @type {SunreiInfoDTO}
     * @memberof MapSunreiSpotDTO
     */
    'sunreiInfo': SunreiInfoDTO;
}
/**
 * 
 * @export
 * @interface MultiSizeImageDTO
 */
export interface MultiSizeImageDTO {
    /**
     * Array of different image sizes (original, large, medium, small)
     * @type {Array<ImageDTO>}
     * @memberof MultiSizeImageDTO
     */
    'images': Array<ImageDTO>;
}
/**
 * 
 * @export
 * @interface PlaceDTO
 */
export interface PlaceDTO {
    /**
     * 
     * @type {string}
     * @memberof PlaceDTO
     */
    'id': string;
    /**
     * Name of the place
     * @type {string}
     * @memberof PlaceDTO
     */
    'name': string;
    /**
     * Address of the place
     * @type {string}
     * @memberof PlaceDTO
     */
    'address'?: string;
    /**
     * Latitude of the place
     * @type {number}
     * @memberof PlaceDTO
     */
    'latitude': number;
    /**
     * Longitude of the place
     * @type {number}
     * @memberof PlaceDTO
     */
    'longitude': number;
    /**
     * Whether the place is permanently closed or no longer exists
     * @type {boolean}
     * @memberof PlaceDTO
     */
    'isClosed': boolean;
    /**
     * Reason for closure (e.g., \"Permanently closed\", \"Demolished\", \"Relocated\")
     * @type {string}
     * @memberof PlaceDTO
     */
    'closedReason'?: string;
    /**
     * Date when the place was closed or ceased to exist
     * @type {string}
     * @memberof PlaceDTO
     */
    'closedAt'?: string;
    /**
     * Additional notes about the place status or history
     * @type {string}
     * @memberof PlaceDTO
     */
    'notes'?: string;
    /**
     * Google Maps Place ID
     * @type {string}
     * @memberof PlaceDTO
     */
    'googleMapsId'?: string;
}
/**
 * 
 * @export
 * @interface SunreiDTO
 */
export interface SunreiDTO {
    /**
     * 
     * @type {string}
     * @memberof SunreiDTO
     */
    'id': string;
    /**
     * Title of the Sunrei
     * @type {string}
     * @memberof SunreiDTO
     */
    'title': string;
    /**
     * Detailed description of the Sunrei
     * @type {string}
     * @memberof SunreiDTO
     */
    'description'?: string;
    /**
     * External link for this Sunrei (program URL or YouTube channel)
     * @type {string}
     * @memberof SunreiDTO
     */
    'link'?: string | null;
    /**
     * Array of multi-size images for this Sunrei
     * @type {Array<MultiSizeImageDTO>}
     * @memberof SunreiDTO
     */
    'images': Array<MultiSizeImageDTO>;
    /**
     * Array of Sunrei spots associated with this Sunrei
     * @type {Array<SunreiSpotDTO>}
     * @memberof SunreiDTO
     */
    'spots': Array<SunreiSpotDTO>;
    /**
     * Array of tags associated with this Sunrei
     * @type {Array<TagDTO>}
     * @memberof SunreiDTO
     */
    'tags': Array<TagDTO>;
    /**
     * 
     * @type {string}
     * @memberof SunreiDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof SunreiDTO
     */
    'updatedAt'?: string;
}
/**
 * 
 * @export
 * @interface SunreiInfoDTO
 */
export interface SunreiInfoDTO {
    /**
     * 
     * @type {string}
     * @memberof SunreiInfoDTO
     */
    'id': string;
    /**
     * Title of the Sunrei
     * @type {string}
     * @memberof SunreiInfoDTO
     */
    'title': string;
    /**
     * Detailed description of the Sunrei
     * @type {string}
     * @memberof SunreiInfoDTO
     */
    'description'?: string;
    /**
     * External link for this Sunrei (program URL or YouTube channel)
     * @type {string}
     * @memberof SunreiInfoDTO
     */
    'link'?: string | null;
    /**
     * Array of multi-size images for this Sunrei
     * @type {Array<MultiSizeImageDTO>}
     * @memberof SunreiInfoDTO
     */
    'images': Array<MultiSizeImageDTO>;
    /**
     * Array of tags associated with this Sunrei
     * @type {Array<TagDTO>}
     * @memberof SunreiInfoDTO
     */
    'tags': Array<TagDTO>;
    /**
     * 
     * @type {string}
     * @memberof SunreiInfoDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof SunreiInfoDTO
     */
    'updatedAt'?: string;
}
/**
 * 
 * @export
 * @interface SunreiSpotDTO
 */
export interface SunreiSpotDTO {
    /**
     * 
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'id': string;
    /**
     * ID of the parent Sunrei
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'sunreiId': string;
    /**
     * Title of the Sunrei Spot
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'title': string;
    /**
     * Detailed description of the Sunrei Spot
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'description'?: string;
    /**
     * YouTube video link for this spot
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'youtubeLink'?: string | null;
    /**
     * Array of multi-size images for this spot
     * @type {Array<MultiSizeImageDTO>}
     * @memberof SunreiSpotDTO
     */
    'images': Array<MultiSizeImageDTO>;
    /**
     * 
     * @type {PlaceDTO}
     * @memberof SunreiSpotDTO
     */
    'place': PlaceDTO;
}
/**
 * 
 * @export
 * @interface TagDTO
 */
export interface TagDTO {
    /**
     * 
     * @type {string}
     * @memberof TagDTO
     */
    'id': string;
    /**
     * Name of the tag
     * @type {string}
     * @memberof TagDTO
     */
    'name': string;
    /**
     * Description of the tag
     * @type {string}
     * @memberof TagDTO
     */
    'description'?: string | null;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get map data (spots with Sunrei info) filtered by polygon
         * @param {string} [polygon] WKT format polygon string (e.g., \&quot;POLYGON((139.5 35.5, 139.8 35.5, 139.8 35.8, 139.5 35.8, 139.5 35.5))\&quot;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMapData: async (polygon?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/map`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (polygon !== undefined) {
                localVarQueryParameter['polygon'] = polygon;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Sunrei by ID
         * @param {string} id ID of the Sunrei to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSunrei: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSunrei', 'id', id)
            const localVarPath = `/api/sunreis/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all places
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlaces: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/places`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all Sunrei
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSunreis: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sunreis`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTags: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/tags`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get map data (spots with Sunrei info) filtered by polygon
         * @param {string} [polygon] WKT format polygon string (e.g., \&quot;POLYGON((139.5 35.5, 139.8 35.5, 139.8 35.8, 139.5 35.8, 139.5 35.5))\&quot;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMapData(polygon?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListMapSpots>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMapData(polygon, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getMapData']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Sunrei by ID
         * @param {string} id ID of the Sunrei to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSunrei(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSunreiResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSunrei(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSunrei']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all places
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPlaces(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PlaceDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPlaces(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listPlaces']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all Sunrei
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSunreis(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSunreiResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSunreis(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listSunreis']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTags(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TagDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTags(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listTags']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Get map data (spots with Sunrei info) filtered by polygon
         * @param {string} [polygon] WKT format polygon string (e.g., \&quot;POLYGON((139.5 35.5, 139.8 35.5, 139.8 35.8, 139.5 35.8, 139.5 35.5))\&quot;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMapData(polygon?: string, options?: RawAxiosRequestConfig): AxiosPromise<ListMapSpots> {
            return localVarFp.getMapData(polygon, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Sunrei by ID
         * @param {string} id ID of the Sunrei to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSunrei(id: string, options?: RawAxiosRequestConfig): AxiosPromise<GetSunreiResult> {
            return localVarFp.getSunrei(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all places
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlaces(options?: RawAxiosRequestConfig): AxiosPromise<Array<PlaceDTO>> {
            return localVarFp.listPlaces(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all Sunrei
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSunreis(options?: RawAxiosRequestConfig): AxiosPromise<ListSunreiResult> {
            return localVarFp.listSunreis(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTags(options?: RawAxiosRequestConfig): AxiosPromise<Array<TagDTO>> {
            return localVarFp.listTags(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Get map data (spots with Sunrei info) filtered by polygon
     * @param {string} [polygon] WKT format polygon string (e.g., \&quot;POLYGON((139.5 35.5, 139.8 35.5, 139.8 35.8, 139.5 35.8, 139.5 35.5))\&quot;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getMapData(polygon?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getMapData(polygon, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Sunrei by ID
     * @param {string} id ID of the Sunrei to retrieve
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getSunrei(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSunrei(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all places
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listPlaces(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listPlaces(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all Sunrei
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listSunreis(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listSunreis(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listTags(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listTags(options).then((request) => request(this.axios, this.basePath));
    }
}



