/* tslint:disable */
/* eslint-disable */
/**
 * Sunrei App API
 * Public map-first API for Sunrei client applications. Distance is always anchored to the map center, never GPS.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BoundsDTO
 */
export interface BoundsDTO {
    /**
     * 
     * @type {number}
     * @memberof BoundsDTO
     */
    'swLat': number;
    /**
     * 
     * @type {number}
     * @memberof BoundsDTO
     */
    'swLng': number;
    /**
     * 
     * @type {number}
     * @memberof BoundsDTO
     */
    'neLat': number;
    /**
     * 
     * @type {number}
     * @memberof BoundsDTO
     */
    'neLng': number;
}
/**
 * 
 * @export
 * @interface GetPlaceResult
 */
export interface GetPlaceResult {
    /**
     * 
     * @type {PlaceDTO}
     * @memberof GetPlaceResult
     */
    'place': PlaceDTO;
    /**
     * 
     * @type {Array<PlaceMentionDTO>}
     * @memberof GetPlaceResult
     */
    'mentions': Array<PlaceMentionDTO>;
    /**
     * 
     * @type {Array<SunreiSpotDTO>}
     * @memberof GetPlaceResult
     */
    'spots': Array<SunreiSpotDTO>;
}
/**
 * 
 * @export
 * @interface GetSourceResult
 */
export interface GetSourceResult {
    /**
     * 
     * @type {SourceDTO}
     * @memberof GetSourceResult
     */
    'source': SourceDTO;
    /**
     * 
     * @type {Array<SunreiSummaryDTO>}
     * @memberof GetSourceResult
     */
    'sunreis': Array<SunreiSummaryDTO>;
    /**
     * 
     * @type {Array<PlaceDTO>}
     * @memberof GetSourceResult
     */
    'places'?: Array<PlaceDTO> | null;
}
/**
 * 
 * @export
 * @interface GetSunreiResult
 */
export interface GetSunreiResult {
    /**
     * 
     * @type {SunreiDTO}
     * @memberof GetSunreiResult
     */
    'sunrei': SunreiDTO;
}
/**
 * 
 * @export
 * @interface ImageDTO
 */
export interface ImageDTO {
    /**
     * 
     * @type {string}
     * @memberof ImageDTO
     */
    'url': string;
    /**
     * 
     * @type {number}
     * @memberof ImageDTO
     */
    'width'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImageDTO
     */
    'height'?: number;
}
/**
 * 
 * @export
 * @interface ListPlacesResult
 */
export interface ListPlacesResult {
    /**
     * 
     * @type {Array<PlaceCardDTO>}
     * @memberof ListPlacesResult
     */
    'places': Array<PlaceCardDTO>;
    /**
     * Optional source rail data for the current map result.
     * @type {Array<SourceDTO>}
     * @memberof ListPlacesResult
     */
    'sources'?: Array<SourceDTO> | null;
    /**
     * 
     * @type {BoundsDTO}
     * @memberof ListPlacesResult
     */
    'bounds'?: BoundsDTO | null;
}
/**
 * 
 * @export
 * @interface ListSourcesResult
 */
export interface ListSourcesResult {
    /**
     * 
     * @type {Array<SourceDTO>}
     * @memberof ListSourcesResult
     */
    'sources': Array<SourceDTO>;
}
/**
 * 
 * @export
 * @interface MultiSizeImageDTO
 */
export interface MultiSizeImageDTO {
    /**
     * 
     * @type {Array<ImageDTO>}
     * @memberof MultiSizeImageDTO
     */
    'images': Array<ImageDTO>;
}
/**
 * One Place = one card = one marker. tags[] is the union of all published spots\' tags at this place (powers client-side tag filter).
 * @export
 * @interface PlaceCardDTO
 */
export interface PlaceCardDTO {
    /**
     * 
     * @type {PlaceDTO}
     * @memberof PlaceCardDTO
     */
    'place': PlaceDTO;
    /**
     * 
     * @type {number}
     * @memberof PlaceCardDTO
     */
    'distanceMeters'?: number | null;
    /**
     * 
     * @type {Array<PlaceMentionDTO>}
     * @memberof PlaceCardDTO
     */
    'mentions': Array<PlaceMentionDTO>;
    /**
     * 
     * @type {Array<TagDTO>}
     * @memberof PlaceCardDTO
     */
    'tags': Array<TagDTO>;
    /**
     * 
     * @type {number}
     * @memberof PlaceCardDTO
     */
    'sourceCount': number;
    /**
     * 
     * @type {number}
     * @memberof PlaceCardDTO
     */
    'sunreiCount': number;
    /**
     * 
     * @type {number}
     * @memberof PlaceCardDTO
     */
    'spotCount': number;
}
/**
 * 
 * @export
 * @interface PlaceDTO
 */
export interface PlaceDTO {
    /**
     * 
     * @type {string}
     * @memberof PlaceDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PlaceDTO
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PlaceDTO
     */
    'address'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PlaceDTO
     */
    'latitude': number;
    /**
     * 
     * @type {number}
     * @memberof PlaceDTO
     */
    'longitude': number;
    /**
     * 
     * @type {string}
     * @memberof PlaceDTO
     */
    'googleMapsId'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PlaceDTO
     */
    'isClosed': boolean;
    /**
     * 
     * @type {string}
     * @memberof PlaceDTO
     */
    'closedReason'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceDTO
     */
    'closedAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceDTO
     */
    'notes'?: string | null;
    /**
     * Optional display text (ward/city) derived from the address, for SpotRows.
     * @type {string}
     * @memberof PlaceDTO
     */
    'areaLabel'?: string | null;
}
/**
 * One mention = one video row in the card. Multiple spots of the same video at the same place collapse into one mention.
 * @export
 * @interface PlaceMentionDTO
 */
export interface PlaceMentionDTO {
    /**
     * 
     * @type {SourceDTO}
     * @memberof PlaceMentionDTO
     */
    'source': SourceDTO;
    /**
     * 
     * @type {string}
     * @memberof PlaceMentionDTO
     */
    'sunreiId': string;
    /**
     * 
     * @type {string}
     * @memberof PlaceMentionDTO
     */
    'sunreiTitle': string;
    /**
     * Representative spot (first with non-empty context).
     * @type {string}
     * @memberof PlaceMentionDTO
     */
    'spotId': string;
    /**
     * 
     * @type {string}
     * @memberof PlaceMentionDTO
     */
    'context'?: string | null;
    /**
     * sunrei.link
     * @type {string}
     * @memberof PlaceMentionDTO
     */
    'sunreiLink'?: string | null;
    /**
     * sunrei_spot.youtube_link deep link
     * @type {string}
     * @memberof PlaceMentionDTO
     */
    'youtubeLink'?: string | null;
    /**
     * 
     * @type {Array<MultiSizeImageDTO>}
     * @memberof PlaceMentionDTO
     */
    'images': Array<MultiSizeImageDTO>;
    /**
     * 
     * @type {Array<TagDTO>}
     * @memberof PlaceMentionDTO
     */
    'tags': Array<TagDTO>;
}
/**
 * 
 * @export
 * @interface PlaceSearchHitDTO
 */
export interface PlaceSearchHitDTO {
    /**
     * 
     * @type {PlaceDTO}
     * @memberof PlaceSearchHitDTO
     */
    'place': PlaceDTO;
    /**
     * 
     * @type {number}
     * @memberof PlaceSearchHitDTO
     */
    'mentionCount': number;
    /**
     * 
     * @type {number}
     * @memberof PlaceSearchHitDTO
     */
    'sourceCount': number;
    /**
     * 
     * @type {number}
     * @memberof PlaceSearchHitDTO
     */
    'distanceMeters'?: number | null;
}
/**
 * Three groups — Areas & places, Channels & programs, and Videos.
 * @export
 * @interface SearchResult
 */
export interface SearchResult {
    /**
     * 
     * @type {Array<PlaceSearchHitDTO>}
     * @memberof SearchResult
     */
    'places': Array<PlaceSearchHitDTO>;
    /**
     * 
     * @type {Array<SourceDTO>}
     * @memberof SearchResult
     */
    'sources': Array<SourceDTO>;
    /**
     * 
     * @type {Array<SunreiSummaryDTO>}
     * @memberof SearchResult
     */
    'sunreis': Array<SunreiSummaryDTO>;
}
/**
 * 
 * @export
 * @interface SourceDTO
 */
export interface SourceDTO {
    /**
     * 
     * @type {string}
     * @memberof SourceDTO
     */
    'id': string;
    /**
     * 
     * @type {SourceType}
     * @memberof SourceDTO
     */
    'type': SourceType;
    /**
     * 
     * @type {string}
     * @memberof SourceDTO
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof SourceDTO
     */
    'nameEn'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceDTO
     */
    'nameKo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceDTO
     */
    'synopsis'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceDTO
     */
    'externalUrl'?: string | null;
    /**
     * 
     * @type {MultiSizeImageDTO}
     * @memberof SourceDTO
     */
    'posterImage'?: MultiSizeImageDTO | null;
    /**
     * 
     * @type {number}
     * @memberof SourceDTO
     */
    'videoCount'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SourceDTO
     */
    'spotCount'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SourceDTO
     */
    'placeCount'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SourceDTO
     */
    'nearestDistanceMeters'?: number | null;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const SourceType = {
    Youtube: 'YOUTUBE',
    Tv: 'TV',
    Anime: 'ANIME',
    Other: 'OTHER'
} as const;

export type SourceType = typeof SourceType[keyof typeof SourceType];


/**
 * 
 * @export
 * @interface SunreiDTO
 */
export interface SunreiDTO {
    /**
     * 
     * @type {string}
     * @memberof SunreiDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SunreiDTO
     */
    'sourceId': string;
    /**
     * 
     * @type {SourceDTO}
     * @memberof SunreiDTO
     */
    'source': SourceDTO;
    /**
     * 
     * @type {string}
     * @memberof SunreiDTO
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof SunreiDTO
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SunreiDTO
     */
    'summary'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SunreiDTO
     */
    'link'?: string | null;
    /**
     * 
     * @type {Array<MultiSizeImageDTO>}
     * @memberof SunreiDTO
     */
    'images': Array<MultiSizeImageDTO>;
    /**
     * 
     * @type {Array<SunreiSpotDTO>}
     * @memberof SunreiDTO
     */
    'spots': Array<SunreiSpotDTO>;
}
/**
 * 
 * @export
 * @interface SunreiSpotDTO
 */
export interface SunreiSpotDTO {
    /**
     * 
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'sunreiId': string;
    /**
     * 
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'title': string;
    /**
     * What this source says here (\"7화에서 주인공이 울며 식사한 식당\").
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'context'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SunreiSpotDTO
     */
    'youtubeLink'?: string | null;
    /**
     * 
     * @type {Array<MultiSizeImageDTO>}
     * @memberof SunreiSpotDTO
     */
    'images': Array<MultiSizeImageDTO>;
    /**
     * 
     * @type {PlaceDTO}
     * @memberof SunreiSpotDTO
     */
    'place': PlaceDTO;
    /**
     * 
     * @type {Array<TagDTO>}
     * @memberof SunreiSpotDTO
     */
    'tags': Array<TagDTO>;
    /**
     * 
     * @type {number}
     * @memberof SunreiSpotDTO
     */
    'distanceMeters'?: number | null;
}
/**
 * 
 * @export
 * @interface SunreiSummaryDTO
 */
export interface SunreiSummaryDTO {
    /**
     * 
     * @type {string}
     * @memberof SunreiSummaryDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SunreiSummaryDTO
     */
    'sourceId': string;
    /**
     * 
     * @type {string}
     * @memberof SunreiSummaryDTO
     */
    'sourceName': string;
    /**
     * 
     * @type {SourceType}
     * @memberof SunreiSummaryDTO
     */
    'sourceType': SourceType;
    /**
     * 
     * @type {string}
     * @memberof SunreiSummaryDTO
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof SunreiSummaryDTO
     */
    'summary'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SunreiSummaryDTO
     */
    'link'?: string | null;
    /**
     * 
     * @type {Array<MultiSizeImageDTO>}
     * @memberof SunreiSummaryDTO
     */
    'images': Array<MultiSizeImageDTO>;
    /**
     * 
     * @type {number}
     * @memberof SunreiSummaryDTO
     */
    'spotCount': number;
    /**
     * 
     * @type {number}
     * @memberof SunreiSummaryDTO
     */
    'placeCount'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SunreiSummaryDTO
     */
    'areaCount'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SunreiSummaryDTO
     */
    'nearestDistanceMeters'?: number | null;
}


/**
 * 
 * @export
 * @interface TagDTO
 */
export interface TagDTO {
    /**
     * 
     * @type {string}
     * @memberof TagDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TagDTO
     */
    'labelEn': string;
    /**
     * 
     * @type {string}
     * @memberof TagDTO
     */
    'labelKo': string;
    /**
     * 
     * @type {string}
     * @memberof TagDTO
     */
    'description'?: string | null;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Nearby mode requires viewport bounds (swLat,swLng,neLat,neLng); centerLat/centerLng is the map-view center used as the distance/sort anchor (computed from bounds center if absent). Source mode is selected by passing sourceIds (comma-separated); it is global (no viewport bound), returns every place featured by the selected source(s), nearest-to-center. If sourceIds is present, source mode wins; otherwise bounds select nearby mode. No tag filtering here — tags are filtered client-side. 
         * @summary List places for the map (nearby or source mode)
         * @param {number} [swLat] 
         * @param {number} [swLng] 
         * @param {number} [neLat] 
         * @param {number} [neLng] 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {string} [sourceIds] Comma-separated source IDs for source mode.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMapData: async (swLat?: number, swLng?: number, neLat?: number, neLng?: number, centerLat?: number, centerLng?: number, sourceIds?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/map`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (swLat !== undefined) {
                localVarQueryParameter['swLat'] = swLat;
            }

            if (swLng !== undefined) {
                localVarQueryParameter['swLng'] = swLng;
            }

            if (neLat !== undefined) {
                localVarQueryParameter['neLat'] = neLat;
            }

            if (neLng !== undefined) {
                localVarQueryParameter['neLng'] = neLng;
            }

            if (centerLat !== undefined) {
                localVarQueryParameter['centerLat'] = centerLat;
            }

            if (centerLng !== undefined) {
                localVarQueryParameter['centerLng'] = centerLng;
            }

            if (sourceIds !== undefined) {
                localVarQueryParameter['sourceIds'] = sourceIds;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get place detail (mentions + spots)
         * @param {string} id 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPlace: async (id: string, centerLat?: number, centerLng?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPlace', 'id', id)
            const localVarPath = `/api/places/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (centerLat !== undefined) {
                localVarQueryParameter['centerLat'] = centerLat;
            }

            if (centerLng !== undefined) {
                localVarQueryParameter['centerLng'] = centerLng;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * YouTube sources return enough data to link out; Anime, TV, and Other return managed-work page data. Videos are sorted by nearest spot to the optional center. 
         * @summary Get a source (source intro / managed work page)
         * @param {string} id 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSource: async (id: string, centerLat?: number, centerLng?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSource', 'id', id)
            const localVarPath = `/api/sources/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (centerLat !== undefined) {
                localVarQueryParameter['centerLat'] = centerLat;
            }

            if (centerLng !== undefined) {
                localVarQueryParameter['centerLng'] = centerLng;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a Sunrei (video preview / video detail)
         * @param {string} id 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSunrei: async (id: string, centerLat?: number, centerLng?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSunrei', 'id', id)
            const localVarPath = `/api/sunreis/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (centerLat !== undefined) {
                localVarQueryParameter['centerLat'] = centerLat;
            }

            if (centerLng !== undefined) {
                localVarQueryParameter['centerLng'] = centerLng;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List sources (source rail / add-source picker)
         * @param {string} [q] 
         * @param {number} [swLat] 
         * @param {number} [swLng] 
         * @param {number} [neLat] 
         * @param {number} [neLng] 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSources: async (q?: string, swLat?: number, swLng?: number, neLat?: number, neLng?: number, centerLat?: number, centerLng?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sources`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (swLat !== undefined) {
                localVarQueryParameter['swLat'] = swLat;
            }

            if (swLng !== undefined) {
                localVarQueryParameter['swLng'] = swLng;
            }

            if (neLat !== undefined) {
                localVarQueryParameter['neLat'] = neLat;
            }

            if (neLng !== undefined) {
                localVarQueryParameter['neLng'] = neLng;
            }

            if (centerLat !== undefined) {
                localVarQueryParameter['centerLat'] = centerLat;
            }

            if (centerLng !== undefined) {
                localVarQueryParameter['centerLng'] = centerLng;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all bilingual tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTags: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/tags`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Database place hits, source hits, and published Sunrei hits. The client may merge Google Places autocomplete results into the places group. Google Places is handled client-side. 
         * @summary Unified search (places, sources, sunreis)
         * @param {string} q 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search: async (q: string, centerLat?: number, centerLng?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('search', 'q', q)
            const localVarPath = `/api/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (centerLat !== undefined) {
                localVarQueryParameter['centerLat'] = centerLat;
            }

            if (centerLng !== undefined) {
                localVarQueryParameter['centerLng'] = centerLng;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Nearby mode requires viewport bounds (swLat,swLng,neLat,neLng); centerLat/centerLng is the map-view center used as the distance/sort anchor (computed from bounds center if absent). Source mode is selected by passing sourceIds (comma-separated); it is global (no viewport bound), returns every place featured by the selected source(s), nearest-to-center. If sourceIds is present, source mode wins; otherwise bounds select nearby mode. No tag filtering here — tags are filtered client-side. 
         * @summary List places for the map (nearby or source mode)
         * @param {number} [swLat] 
         * @param {number} [swLng] 
         * @param {number} [neLat] 
         * @param {number} [neLng] 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {string} [sourceIds] Comma-separated source IDs for source mode.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMapData(swLat?: number, swLng?: number, neLat?: number, neLng?: number, centerLat?: number, centerLng?: number, sourceIds?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPlacesResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMapData(swLat, swLng, neLat, neLng, centerLat, centerLng, sourceIds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getMapData']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get place detail (mentions + spots)
         * @param {string} id 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPlace(id: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetPlaceResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPlace(id, centerLat, centerLng, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getPlace']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * YouTube sources return enough data to link out; Anime, TV, and Other return managed-work page data. Videos are sorted by nearest spot to the optional center. 
         * @summary Get a source (source intro / managed work page)
         * @param {string} id 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSource(id: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSourceResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSource(id, centerLat, centerLng, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSource']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a Sunrei (video preview / video detail)
         * @param {string} id 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSunrei(id: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSunreiResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSunrei(id, centerLat, centerLng, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSunrei']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List sources (source rail / add-source picker)
         * @param {string} [q] 
         * @param {number} [swLat] 
         * @param {number} [swLng] 
         * @param {number} [neLat] 
         * @param {number} [neLng] 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSources(q?: string, swLat?: number, swLng?: number, neLat?: number, neLng?: number, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSourcesResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSources(q, swLat, swLng, neLat, neLng, centerLat, centerLng, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listSources']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all bilingual tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTags(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TagDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTags(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listTags']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Database place hits, source hits, and published Sunrei hits. The client may merge Google Places autocomplete results into the places group. Google Places is handled client-side. 
         * @summary Unified search (places, sources, sunreis)
         * @param {string} q 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search(q: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search(q, centerLat, centerLng, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.search']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Nearby mode requires viewport bounds (swLat,swLng,neLat,neLng); centerLat/centerLng is the map-view center used as the distance/sort anchor (computed from bounds center if absent). Source mode is selected by passing sourceIds (comma-separated); it is global (no viewport bound), returns every place featured by the selected source(s), nearest-to-center. If sourceIds is present, source mode wins; otherwise bounds select nearby mode. No tag filtering here — tags are filtered client-side. 
         * @summary List places for the map (nearby or source mode)
         * @param {number} [swLat] 
         * @param {number} [swLng] 
         * @param {number} [neLat] 
         * @param {number} [neLng] 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {string} [sourceIds] Comma-separated source IDs for source mode.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMapData(swLat?: number, swLng?: number, neLat?: number, neLng?: number, centerLat?: number, centerLng?: number, sourceIds?: string, options?: RawAxiosRequestConfig): AxiosPromise<ListPlacesResult> {
            return localVarFp.getMapData(swLat, swLng, neLat, neLng, centerLat, centerLng, sourceIds, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get place detail (mentions + spots)
         * @param {string} id 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPlace(id: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetPlaceResult> {
            return localVarFp.getPlace(id, centerLat, centerLng, options).then((request) => request(axios, basePath));
        },
        /**
         * YouTube sources return enough data to link out; Anime, TV, and Other return managed-work page data. Videos are sorted by nearest spot to the optional center. 
         * @summary Get a source (source intro / managed work page)
         * @param {string} id 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSource(id: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetSourceResult> {
            return localVarFp.getSource(id, centerLat, centerLng, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a Sunrei (video preview / video detail)
         * @param {string} id 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSunrei(id: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetSunreiResult> {
            return localVarFp.getSunrei(id, centerLat, centerLng, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List sources (source rail / add-source picker)
         * @param {string} [q] 
         * @param {number} [swLat] 
         * @param {number} [swLng] 
         * @param {number} [neLat] 
         * @param {number} [neLng] 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSources(q?: string, swLat?: number, swLng?: number, neLat?: number, neLng?: number, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig): AxiosPromise<ListSourcesResult> {
            return localVarFp.listSources(q, swLat, swLng, neLat, neLng, centerLat, centerLng, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all bilingual tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTags(options?: RawAxiosRequestConfig): AxiosPromise<Array<TagDTO>> {
            return localVarFp.listTags(options).then((request) => request(axios, basePath));
        },
        /**
         * Database place hits, source hits, and published Sunrei hits. The client may merge Google Places autocomplete results into the places group. Google Places is handled client-side. 
         * @summary Unified search (places, sources, sunreis)
         * @param {string} q 
         * @param {number} [centerLat] 
         * @param {number} [centerLng] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search(q: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig): AxiosPromise<SearchResult> {
            return localVarFp.search(q, centerLat, centerLng, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Nearby mode requires viewport bounds (swLat,swLng,neLat,neLng); centerLat/centerLng is the map-view center used as the distance/sort anchor (computed from bounds center if absent). Source mode is selected by passing sourceIds (comma-separated); it is global (no viewport bound), returns every place featured by the selected source(s), nearest-to-center. If sourceIds is present, source mode wins; otherwise bounds select nearby mode. No tag filtering here — tags are filtered client-side. 
     * @summary List places for the map (nearby or source mode)
     * @param {number} [swLat] 
     * @param {number} [swLng] 
     * @param {number} [neLat] 
     * @param {number} [neLng] 
     * @param {number} [centerLat] 
     * @param {number} [centerLng] 
     * @param {string} [sourceIds] Comma-separated source IDs for source mode.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getMapData(swLat?: number, swLng?: number, neLat?: number, neLng?: number, centerLat?: number, centerLng?: number, sourceIds?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getMapData(swLat, swLng, neLat, neLng, centerLat, centerLng, sourceIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get place detail (mentions + spots)
     * @param {string} id 
     * @param {number} [centerLat] 
     * @param {number} [centerLng] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getPlace(id: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getPlace(id, centerLat, centerLng, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * YouTube sources return enough data to link out; Anime, TV, and Other return managed-work page data. Videos are sorted by nearest spot to the optional center. 
     * @summary Get a source (source intro / managed work page)
     * @param {string} id 
     * @param {number} [centerLat] 
     * @param {number} [centerLng] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getSource(id: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSource(id, centerLat, centerLng, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a Sunrei (video preview / video detail)
     * @param {string} id 
     * @param {number} [centerLat] 
     * @param {number} [centerLng] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getSunrei(id: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSunrei(id, centerLat, centerLng, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List sources (source rail / add-source picker)
     * @param {string} [q] 
     * @param {number} [swLat] 
     * @param {number} [swLng] 
     * @param {number} [neLat] 
     * @param {number} [neLng] 
     * @param {number} [centerLat] 
     * @param {number} [centerLng] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listSources(q?: string, swLat?: number, swLng?: number, neLat?: number, neLng?: number, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listSources(q, swLat, swLng, neLat, neLng, centerLat, centerLng, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all bilingual tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listTags(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listTags(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Database place hits, source hits, and published Sunrei hits. The client may merge Google Places autocomplete results into the places group. Google Places is handled client-side. 
     * @summary Unified search (places, sources, sunreis)
     * @param {string} q 
     * @param {number} [centerLat] 
     * @param {number} [centerLng] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public search(q: string, centerLat?: number, centerLng?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).search(q, centerLat, centerLng, options).then((request) => request(this.axios, this.basePath));
    }
}



