apiVersion: v1
kind: Secret
metadata:
    name: sunrei-secrets
    namespace: sunrei
type: Opaque
stringData:
    google-maps-map-id: ENC[AES256_GCM,data:9TY6QYXvXKmHw6o=,iv:uE56Ie8aC1hIVlRZMz91X3MzyTOrBnRfT2C5h+bsGRg=,tag:I20L2salk1v/0lga2g6hWg==,type:str]
    google-maps-api-key: ENC[AES256_GCM,data:5xrKsTSc3vHSZ3SEGnhZhdQQEsn4ThVp9SBd1FPepX67kQ1Ir7W+,iv:pjqq2px1tDIaPIlRJAsk+F/DIzRvlrYnYv8giN4J/ro=,tag:CpqfIHCx1/IdIR5qk91oXQ==,type:str]
    jwt-page-token-secret: ENC[AES256_GCM,data:d1JMyIeFu6I6SJnWwA==,iv:DkpEb26W84lrOy2xYFKe6eIMpfk0SNByQTT9maf0XPQ=,tag:6yRR1Au+MN/QjCQgFNRvKg==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:I6/u+OtQp06j39vwk1OCzFUGDz0=,iv:5MVkpeWuROWBv6i+HbC0uitCqJMZq6zl8CxSMSOM7qw=,tag:1vGc+d7Pv/6neqzsGNcdXA==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:QKF326zkYaJ7/zHR+yXJCppGPpKVIM85ERreXbb35LMUDZsVYXe/GQ==,iv:uKLGoXa/FfmWWFagLRGh+7S3/22sxHIC1IA4McO2PSA=,tag:74cXYIZbjptodTQ2ehFBoA==,type:str]
    google-oauth-client-id: ENC[AES256_GCM,data:Yq5dp6X2Dp6EJLXnNvs8A5/N2PUpQvWIh3tlgowSopv1nJnjAHDAH4tx/2z3rjQNhPJo6kES3kNKJF86Zr1X4p5yGarNf6uK,iv:084alSs06eFQKaRUkyRZrcxV247B5Hap+HRWOnItk9E=,tag:6HoPHYnrmqClZ56GeLk6kQ==,type:str]
    google-oauth-client-secret: ENC[AES256_GCM,data:CRzxnQV8slJRxdmRJtL23F8WOQ8xLtoJ6XPOfBKFFN3rWeo=,iv:lwvquJUeXHnSscQKhxC/7jufOKUjb1p+5P+7tVEVvs0=,tag:7D2vw3L9keKBYHig42MH8A==,type:str]
    auth-jwt-secret: ENC[AES256_GCM,data:ZWzDo38CjqEfEUGnSi0=,iv:OFNk0ROm6vPZ7LORbxVxxtUKfLdQvToRSWVH0s6DElY=,tag:/anO1bfSCulSXT4o6/3hqw==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/default-487602/locations/asia-northeast3/keyRings/homelab-secrets/cryptoKeys/sops-key
          created_at: "2026-02-16T03:26:23Z"
          enc: CiQAcUuTffwsCGC6hFt6BuyytZ8oiq3SvKvnO2uU98wMKPaTmWYSSQBpUNVoGS+2SwwOfhv3NkL0tWLnHj5uDu+u9QnKT+fSEBupjlwCz3nOaavMS2AZTI3ssD9PK/2zTEIk2mtWMCow2OUlUGHEQv8=
    lastmodified: "2026-07-26T07:13:08Z"
    mac: ENC[AES256_GCM,data:+PUBypxQW65r2zvGOQMrZ39f+sjTzaIW5jwx/9s2pSnMGt7t0WTeBmYsaQYrTouBwgSMX5/5dU8K0geqI1u4Fk5agByh6ogK1/Vvkyxe7NiTylEzNR3Mn4tkxKihpbnzH/QW5FZ/zsWp2YScIuGLlLPLOe/6PeUz+q2pgS+NRPQ=,iv:KFkAKq7Bc3snKJK4H9NPPSin2crmMqMZN5wDUDIOxhU=,tag:pOfcUfVc6TC414LUXSqzew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
